#!/usr/bin/env python3

#Filename: m2p3.py
#Author: Cole Sanheim
#Course: ITSC203
#Details: This program utalizes pefile and a manual method to read information about a .exe file
#Resources: https://docs.python.org/3/library/

import sys
import pefile
import time
import datetime
from datetime import datetime

today = datetime.now()
pe = pefile.PE(sys.argv[1])
#print(pe.dump_info())
print("Report generated by: Coleton Sanheim")
print("Contact\t\t:coleton.sanheim@edu.sait.ca")
print("Date/Time\t:" + today.strftime("%B-%d-%Y %I:%M:%S") + " (UTC: " + str(int(time.time())) + ")")
print("From pefile module:")
print("\tFile\t\t\t:" + sys.argv[1])
print("\tMagic\t\t\t:" + str(hex(pe.DOS_HEADER.e_magic)))
print("\tPE Header Offset\t:" + str(hex(pe.DOS_HEADER.e_lfanew)))
if hex(pe.FILE_HEADER.Machine) == '0x14c':
    print("\tFormat\t\t\t:32 bit")
elif hex(pe.FILE_HEADER.Machine) == '0x8664':
    print("\tFormat\t\t\t:64 bit")
print("\tEndian\t\t\t:big")
print("\tMachine\t\t\t:" + str(hex(pe.FILE_HEADER.Machine)))
print("\tEntry Point\t\t:" + str(hex(pe.OPTIONAL_HEADER.AddressOfEntryPoint)))

f = open(sys.argv[1], "rb")
print("\nFrom manual method:")
print("\tFile\t\t\t:" + sys.argv[1])
f.seek(0x0)
print("\tMagic\t\t\t:" + str(f.read(2).hex()))
f.seek(0x3C)
print("\tPE Header Offset\t:" + str(f.read(1).hex()))
f.seek(0xFC)
test = f.read(2).hex()
if test == 'c14':
    print("\tFormat\t\t\t:32 bit")
elif test == '6486':
    print("\tFormat\t\t\t:64 bit")
print("\tEndian\t\t\t:little")
f.seek(0xFC)
print("\tMachine\t\t\t:" + str(f.read(2).hex()))
f.seek(0x120)
print("\tEntry Point\t\t:" + str(f.read(3).hex()))
f.close()

#question 1: its where the execution of a program begins, and where the program has access to command line arguments
#question 2: its how the computer differentiate between and recognize different files without a file extenstion
#question 3: No it will not, as it will not be reconised as an executable file anymore
#question 4: It didnt, by changing the magic number the file extention was changed and an error was outputted
#question 5: Overall it was pretty similar to use pefile compared to doing it manually, the main benifit of doing it with pefile however is that you dont need to know the specific offset of a value to find the value